### ISSUE TITLE
dependencies: geocore blocks geobase upgrade

### ISSUE THREAD

**Issue by tomquas** [navibyte/geospatial#241]
we're using both _geocore and geobase_ in the same project and want to upgrade geobase to 1.x.

code in use:
```
final feature = GeoJSON().parserGeographic(GeoPoint2.coordinates).feature(json);
```

actual behavior: we are blocked by a false(?) dependency in geocore's [pubspec.yaml](https://github.com/navibyte/geospatial/blob/6bb621ff89d0bc5302dec54afee73e2442c26d1f/dart/geocore/pubspec.yaml#L14).

expected behavior: be able to add both geocore and geobase to project's pubspec.yaml

UPDATE

we tried to replace package geocore with package geodata, but ran into
```
Resolving dependencies... 
Because google_fonts >=4.0.5 depends on http ^1.0.0 and geodata >=0.9.0-dev.4 depends
  on http ^0.13.0, google_fonts >=4.0.5 is incompatible with geodata >=0.9.0-dev.4.
So, because <project> depends on both geodata ^1.2.0 and google_fonts ^6.2.0, version
  solving failed.
```

package geodata should upgrade its dependencies and probably be less picky on external dependency versions. maybe just 'any'?

**Comment by navispatial** [comment]
Thanks for feedback and sorry about inconsistencies on package dependencies.

Status of these packages as described in the [repository readme page](https://github.com/navibyte/geospatial?tab=readme-ov-file#building_construction-roadmap)
* `geobase` and `geodata` packages are still active, not updated very frequently, but still developed (as other projects allow to use some time on these)
* `geocore` is not updated anymore since the latest version `0.10.1`

There is some dependency issues, as you have noted. If you use latest `geocore`, then `geobase` version 0.3.0 (as referenced in pubspec.yaml of geocore) is the last version that is surely compatible with `geocore` and vice versa.

Since then starting from `geobase` version 0.4.0 and at least in version 1.x.x the development of `geobase` went it's own path (and propably `geocore` is not anymore compatible with these). At this point it should have been better to introduce a new package instead of creating these dependency issues, but this is now too late to note.

**If just possible it's recommended to upgrade and refactor apps using these packages to use `geobase` package instead of `geocore`**. The `geobase` should now have much more larger set of features. Is there some specific function in `geocore` that you find missing in `geobase` (the latest version)?

To parse GeoJSON string you do not need `geodata` (that extends `geobase` with some API capabilities on GeoJSON / OGC API web resources). You can use `geobase` as documented here:

https://geospatial.navibyte.dev/v1/geobase/formats/

If your `json` variable contains a `GeoJSON Feature` object, you should use code like `Feature.parse(json, format: GeoJSON.feature);` to parse a Feature object.

Such a feature object may contain point, line string, polygon and multi geometries. By default coordinates inside such geometries are  of type `Position` and `PositionSeries` that can contain either geographic or projected coordinates. This has changed radically from `geocore`. This is discussed in documentation: https://geospatial.navibyte.dev/v1/geobase/coordinates/

Next updates to `geobase` and `geodata` may go to november 2024 - no time slots left in October. Anyway your note about *package geodata should upgrade its dependencies and probably be less picky on external dependency versions. maybe just any* should be checked then....

**Comment by tomquas** [comment]
thank you for responding so quick. we will try to replace geocore as you suggested. looking forward to the upcoming changes.
