### ISSUE TITLE
Coordinate reference system (`CRS`) identifiers enhanced

### ISSUE THREAD

**Issue by navibyte** [navibyte/geospatial#28]
* Coordinate reference system (`CRS`) identifiers
* Enhanced support for **most** common CRS values
* CRS properties on geometries (should every class have or only collections?)

**Comment by navispatial** [comment]
Coordinate reference system (CRS) identifiers are used in some places, for example:
* `geobase`
   * class `SpatialExtent` has `crs` property
   * mixin `ProjectionAdapter` has `fromCrs` and `toCrs` properties
* `geodata`
  * class `GeospatialQuery` has `crs` property

These use case use `String` type for `crs` properties, allowing any string, but using some constants like `OGCFeatureClient` referring to "http://www.opengis.net/def/crs/OGC/1.3/CRS84" as specified by OGC API Features standard. Or `WebMercatorProjection` class refers to a well-known String constant "EPSG:4326".

It might be an improvement to have most common CRS identifiers defined somewhere as constants or enums. Maybe such place should be a separate package that different geospatial package could then refer instead of every package defining own set of contants/enums. 

Currently no such definitions planned for `geobase` and/or `geodata` packages. Maybe would need that separate package in future and then utilize that? Or just use String values and let clients define identifier they need.
